### ISSUE TITLE
pvig_m_224_gelu无法使用

### ISSUE THREAD

**Issue by fanfanfan-hff** [huawei-noah/Efficient-AI-Backbones#113]
下载预训练的pvig_m_224_gelu模型后，执行`python train.py ../../../datasets/ImageNet --model pvig_m_224_gelu --pretrain_path model/pvig_m_83.1.pth.tar --evaluate`出错：
```python
Traceback (most recent call last):
  File "train.py", line 815, in <module>
    main()
  File "train.py", line 337, in main
    model = create_model(
  File "anaconda3/envs/vig/lib/python3.8/site-packages/timm/models/factory.py", line 57, in create_model
    model = create_fn(**model_args, **kwargs)
  File "code/vig/vig_pytorch/pyramid_vig.py", line 241, in pvig_m_224_gelu
    model = DeepGCN(opt)
  File "code/vig/vig_pytorch/pyramid_vig.py", line 137, in __init__
    Seq(Grapher(channels[i], num_knn[idx], min(idx // 4 + 1, max_dilation), conv, act, norm,
  File "code/vig/vig_pytorch/gcn_lib/torch_vertex.py", line 157, in __init__
    relative_pos_tensor = torch.from_numpy(np.float32(get_2d_relative_pos_embed(in_channels,
  File "code/vig/vig_pytorch/gcn_lib/pos_embed.py", line 27, in get_2d_relative_pos_embed
    pos_embed = get_2d_sincos_pos_embed(embed_dim, grid_size)
  File "code/vig/vig_pytorch/gcn_lib/pos_embed.py", line 50, in get_2d_sincos_pos_embed
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
  File "code/vig/vig_pytorch/gcn_lib/pos_embed.py", line 60, in get_2d_sincos_pos_embed_from_grid
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
  File "code/vig/vig_pytorch/gcn_lib/pos_embed.py", line 74, in get_1d_sincos_pos_embed_from_grid
    assert embed_dim % 2 == 0
AssertionError
```
而另外三个都可以正常运行、测试

**Comment by fanfanfan-hff** [comment]
请问应该怎么使用呢

**Comment by iamhankai** [comment]
不好意思，有个参数写错了，现在ok了

**Comment by goodmorningsi** [comment]
> 不好意思，有个参数写错了，现在ok了
您好，我也遇到了与这相似的问题，请问要怎么解决呢
`using relative_pos
    relative_pos_tensor = torch.from_numpy(np.float32(get_2d_relative_pos_embed(in_channels,      
  File "D:\mask_rcnn\gcn_libs\pos_embed.py", line 27, in get_2d_relative_pos_embed
    pos_embed = get_2d_sincos_pos_embed(embed_dim, grid_size)
  File "D:\mask_rcnn\gcn_libs\pos_embed.py", line 50, in get_2d_sincos_pos_embed
    pos_embed = get_2d_sincos_pos_embed_from_grid(embed_dim, grid)
  File "D:\mask_rcnn\gcn_libs\pos_embed.py", line 60, in get_2d_sincos_pos_embed_from_grid        
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
  File "D:\mask_rcnn\gcn_libs\pos_embed.py", line 73, in get_1d_sincos_pos_embed_from_grid        
    assert embed_dim % 2 == 0
AssertionError
`

**Comment by goodmorningsi** [comment]
@iamhankai

**Comment by iamhankai** [comment]
我刚才又用timm 0.3.2跑了一遍，没啥问题啊

**Comment by goodmorningsi** [comment]
> 我刚才又用pytorch 1.8.0, timm 0.3.2跑了一遍，没啥问题啊

会不会是我替换backbone的时候出了问题呀，我在mask_rcnn的train文件里像这样替换了一下，还有哪些部分没有修改到吗？
![bb3f53f9f5f50bebee728d73c5f63f6](https://user-images.githubusercontent.com/97372086/220096797-27b8237a-6ace-480e-8bdc-d6537c9062b3.png)

**Comment by iamhankai** [comment]
你替换后relative_pos的尺寸需要改一下，让他适配检测的输入大小
