### ISSUE TITLE
改成自己的数据集后target变量尺寸不对

### ISSUE THREAD

**Issue by PoisonKiller** [huawei-noah/Efficient-AI-Backbones#246]
我的数据集是90分类，我从0开始训练这个模型的时候，改了num_class=90，但是会出现说target变量尺寸不match
Traceback (most recent call last):
  File "train.py", line 817, in <module>
    main()
  File "train.py", line 609, in main
    train_metrics = train_epoch(
  File "train.py", line 682, in train_epoch
    loss = loss_fn(output, target)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/timm/loss/cross_entropy.py", line 35, in forward
    loss = torch.sum(-target * F.log_softmax(x, dim=-1), dim=-1)
RuntimeError: The size of tensor a (1000) must match the size of tensor b (90) at non-singleton dimension 1
查看发现target的尺寸为torch.Size([128, 1000]),请问应该怎么修改呢？

**Comment by PoisonKiller** [comment]
这个问题解决了。
